Repository una-auxme/paf, pull requests merged in 2023-11, with the labels that each got.

#2 1 - Update README.md
  README.md
Labels: good first issue

#27 fix(#26): Updated project URL
  .github/workflows/add-to-project.yml
  LICENSE
Labels: bug

#50 Fixed permissions for project folders
  build/docker-compose.yml
Labels: bug

#35 3 - Research: Pylot perception
  doc/03_research/02_perception/04_pylot.md
  doc/03_research/02_perception/Readme.md
Labels: Research

#36 10 - Research: PAF21-1 planning
  doc/03_research/03_planning/08_paf21-1.md
  doc/03_research/03_planning/Readme.md
Labels: Research

#45 Research results for Acting of PAF21_1 and Autoware
  doc/03_research/01_acting/autoware_acting.md
  doc/03_research/01_acting/paf21_1_Acting.md
Labels: Research

#68 Add in-depth documentation for Acting, including a neat diagram of the inner architecture and ToDo's for future work
  doc/00_assets/acting/inner_architecture.png
  doc/05_acting/05_documentation_components.md
  doc/05_acting/Readme.md
Labels: documentation, research, acting

#70 69 feature documentation of changes from leaderboard 20
  doc/00_assets/leaderboard-1.png
  doc/00_assets/leaderboard-2.png
  doc/03_research/Leaderboard-2/capture_sensor_data.py
  doc/03_research/Leaderboard-2/changes_leaderboard2.md
Labels: documentation

#67 [Feature]: Cleaning up the github repository documentation
  doc/00_assets/research_assetes/messages_paf21_2.png
  doc/00_assets/research_assetes/mpc.png
  doc/00_assets/research_assetes/pure_pursuit.png
  doc/00_assets/research_assetes/standard_routine_paf21_2.png
  doc/00_assets/research_assetes/stanley_controller.png
  doc/03_research/01_acting/03_paf21_1_Acting.md
  doc/03_research/01_acting/04_research_Acting_Pylot_and_PAF21_2.md
  doc/03_research/01_acting/05_autoware_acting.md
  doc/03_research/01_acting/Readme.md
  doc/03_research/02_perception/05_Research_PAF21-Perception.md
  doc/03_research/02_perception/Readme.md
  doc/03_research/03_planning/09_Research_Pylot_Planning.md
  doc/03_research/03_planning/Readme.md
  doc/08_dev_talks/dev_talks_paf22/sprint_4.md
  doc/08_dev_talks/dev_talks_paf22/sprint_5.md
  doc/08_dev_talks/dev_talks_paf23/sprint_1.md
Labels: documentation, research

#74 Add documentation for Planning in Paf22
  doc/03_research/03_planning/00_paf23/02_PlanningPaf22.md
  doc/03_research/03_planning/00_paf23/overview.jpg
Labels: documentation

#65 [Feature] #64 - Add ability to specify map in Dataset-Generator
  code/perception/src/dataset_generator.py
  doc/06_perception/01_dataset_generator.md
Labels: enhancement

#71 54 - Add model evaluation experiment for perception
  doc/06_perception/experiments/model_evaluation/README.md
  doc/06_perception/experiments/model_evaluation/asset-copies/1619_PT_fasterrcnn_resnet50_fpn_v2.jpg
  doc/06_perception/experiments/model_evaluation/asset-copies/1619_TF_faster-rcnn.jpg
  doc/06_perception/experiments/model_evaluation/asset-copies/1619_yolo_nas_l.jpg
  doc/06_perception/experiments/model_evaluation/asset-copies/1619_yolo_rtdetr_x.jpg
  doc/06_perception/experiments/model_evaluation/asset-copies/1619_yolov8x.jpg
  doc/06_perception/experiments/model_evaluation/asset-copies/1619_yolov8x_seg.jpg
  doc/06_perception/experiments/model_evaluation/globals.py
  doc/06_perception/experiments/model_evaluation/pt.py
  doc/06_perception/experiments/model_evaluation/pylot.py
  doc/06_perception/experiments/model_evaluation/requirements.txt
  doc/06_perception/experiments/model_evaluation/yolo.py
Labels: documentation, research, perception

#90 63 - Fix add-to-project action
  .github/workflows/add-to-project.yml
Labels: bug, infrastructure

#93 38 - Allow writing for all users
  build/docker-compose.yml
Labels: bug, infrastructure

#100 75 feature architecture for planning
  doc/03_research/03_planning/00_paf23/Globalplan.png
  doc/03_research/03_planning/00_paf23/architecture.md
  doc/03_research/03_planning/00_paf23/localplan.png
  doc/03_research/03_planning/00_paf23/overview.png
  doc/03_research/03_planning/00_paf23/prios.png
Labels: planning

#97 96 - Add LaneNet evaluation
  doc/06_perception/experiments/lanenet_evaluation/README.md
  doc/06_perception/experiments/lanenet_evaluation/assets/1600_lanes.jpg
  doc/06_perception/experiments/lanenet_evaluation/assets/1600_lanes_mask.jpg
  doc/06_perception/experiments/lanenet_evaluation/assets/1619_lanes.jpg
  doc/06_perception/experiments/lanenet_evaluation/assets/1619_lanes_mask.jpg
  doc/06_perception/experiments/lanenet_evaluation/assets/1660_lanes.jpg
  doc/06_perception/experiments/lanenet_evaluation/assets/1660_lanes_mask.jpg
  doc/06_perception/experiments/lanenet_evaluation/assets/1663_lanes.jpg
  doc/06_perception/experiments/lanenet_evaluation/assets/1663_lanes_mask.jpg
Labels: research, perception

#98 86 new segmentation node
  code/agent/config/rviz_config.rviz
  code/perception/launch/perception.launch
  code/perception/src/vision_node.py
  doc/06_perception/07_vision_node.md
Labels: perception

#56 [Fix] #37 - Fix build process and run for Carla Agent docker image
  build/docker-compose.yml
  build/docker/agent/Dockerfile
  code/perception/src/coordinate_transformation.py
  code/requirements.txt
Labels: infrastructure

#94 Added dockerfile for CARLA submission
  build/docker/agent/Dockerfile_Submission
Labels: infrastructure
